#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 13 12:42:34 2019

@author: AJRasure
"""

def main():
    #initialize variables   
    z = 10000 #terms to run
    m = 2
    fiboSeq = [0,1]
    divList = []
    #create terms
    for ii in range(2,z):
        fiboSeq.append(fiboSeq[ii-2]+fiboSeq[ii-1])
     
    for ii in range(0,z):
        if fiboSeq[ii]%m == 0:
            divList.append(fiboSeq[ii])
    
    print(divList)
    print(len(fiboSeq))
    print(len(divList))
    print()
    print(len(divList)/len(fiboSeq)*100)
main()